import("//kernel/liteos_m/liteos.gni")

module_name = get_path_info(rebase_path("."), "name")
kernel_module(module_name) {
    sources = [
        "startup_ing91600.s",
    ]
}

config("public") {
    cflags  = []
    lib_dirs =["$root_out_dir/libs" ]
    print("lib_dir are: ${lib_dirs}")
    test_step = "part1" #?????????????????
    
    ldflags = [
        "-Wl,-T" + rebase_path("ing916.ld"),
        "-Wl,--whole-archive",
        #"-lbootstrap",
        #"-lbroadcast",
        #"-lhctest",
       # "-lapp_hello",
       ]
       
    #xtspart1
    if (test_step == "part1") {
    ldflags += [
        #"-ldevattest_sdk",
        #"-ldevattest_core",
        #"-lcjson_static",  
        #"-lhal_token_static",
       #"-lhal_sysparam",
       #"-lmodule_ActsBootstrapTest",#??
       #"-lmodule_ActsParameterTest",#?? 
    ]
    }       

    #xtspart2
    #test\xts\acts\distributed_schedule_lite\system_ability_manager_hal\BUILD.gn
    #?????,??????c??
    else if (test_step == "part2") {
    cflags += [
    "-UINTER_ATTEST_MINI_MODULE",
    ]
    ldflags += [
       "-lmodule_ActsSamgrTest",
      ]
    }
     
    #xtspart3 flash??,?????:make menuconfig?kernel???????flash??
    #test\xts\acts\security_lite\huks\liteos_m_adapter\BUILD.gn
    else if (test_step == "part3"){
    cflags += ["-UINTER_ATTEST_MINI_MODULE"]
    ldflags += [
       "-lhuks_test_common",#pass
       "-lmodule_ActsHuksHalFunctionTest",#pass
    ]
    }

    
    ####xtspart4       
    else if (test_step == "part4"){
    cflags += ["-UINTER_ATTEST_MINI_MODULE"]
    ldflags += [
       "-lmodule_ActsDfxFuncTest",#??
       "-lmodule_ActsUpdaterFuncTest",#??
       "-lmodule_ActsHieventLiteTest",#??
       ]
    }

       
    ####xtspart5 make menuconfig?kernel???????flash??
    else if (test_step == "part5") {
    cflags += ["-UINTER_ATTEST_MINI_MODULE"]
    ldflags += [
       "-lmodule_ActsUtilsFileTest",#??flash??
    ]
    }

    ldflags += [
            "-Wl,--no-whole-archive",
    ]
print("ldflags are:${ldflags}")    
}